spring:
  application:
    name: bootcamp

  datasource:
    url: jdbc:mysql://localhost:3306/bootcamp
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083